## This function creates a special object that stores matrix and cache's its inverse.

## More specifically it creats a special matrix composed of a list of functions listed below:
## 1. set the value of the matrix
## 2. get the value of the matrix
## 3. set the value of the inverse
## 4. get the value of the inverse
makeCacheMatrix <- function(x = matrix()) {
  m <- NULL
set <- function(y = matrix()) {
  x <<- y
  m <<- NULL
}
get <- function() x
setinverse <- function(inverse) m <<- inverse
getinverse <- function() m
list(set = set, get = get,
     setinverse = setinverse,
     getinverse = getinverse)

}

## This function calculates the inverse of the matrix generated by the above function. 


cacheSolve <- function(x, ...) {
  m <- x$getinverse()
if(!is.null(m)) {
  message("getting cached data")
  return(m)
}
data <- x$get()
m <- solve(data, ...)
x$setinverse(m)
m
        ## Return a matrix that is the inverse of 'x'
}
